---
- import_tasks: tasks/amzn2.yml
  when:
    ansible_distribution == "Amazon" and ansible_distribution_version == '2'

- import_tasks: tasks/centos.yml
  when:
    ansible_distribution == "CentOS"

- name: install nginx
  yum:
    name: nginx
    state: present
  become: true
