---

- name: create yum repository file
  copy:
    src: etc/yum.repos.d/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
  become: true

- name: install nginx
  yum:
    name: nginx
    state: present
  become: true
