---

- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
  become: true
  delegate_to: "{{item}}"
  run_once: true
  when: hostvars[item].change_mycnf | changed
  with_items: '{{ play_hosts }}'
