---

- name: install zabbix repository
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
  become: true

- name: install zabbix-agent
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "zabbix-agent"
  become: true

- name: start zabbix-agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  become: true
